[tool.ruff]
line-length = 88

[tool.ruff.lint.per-file-ignores]
"fitDash/settings/__init__.py" = ["F403"]
"fitDash/settings/*.py" = ["F401"]


[pytest]
DJANGO_SETTINGS_MODULE = fitDash.settings
python_files = tests.py test_*.py *_tests.py