name: CI/CD com Django e PostgreSQL

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Instalar Ruff
      run: pip install ruff

    - name: Executar Ruff Lint
      run: ruff check .


    - name: Configurar .env para CI
      run: |
        echo "POSTGRES_USER=testuser" >> .env
        echo "POSTGRES_DB=testdb" >> .env
        echo "POSTGRES_PASSWORD=testpassword" >> .env
        echo "DB_PORT=5432" >> .env
        echo "ACCESS_TIME=3600" >> .env
        echo "REFRESH_TIME=86400" >> .env
        echo "DEBUG=True" >> .env
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTS_PASSWORD }}


    - name: build docker
      run: docker compose up --build -d --wait

    - name: Obter logs do DB se a inicialização falhou
      if: failure()
      run: |
        echo "Iniciando coleta de logs do fitdashboard-db..."
        docker compose logs fitdashboard-db
        echo "Coleta de logs concluída."

    - name: Parar e remover Docker Compose
      if: always()
      run: docker compose down
